project:
  type: website
  execute-dir: file
  
lang: es

website:
  title: "Cambio climatico, plagas y manzanas"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: facebook
        href: https://facebook.com
    format:
      html:
        theme: cosmo
        css: styles.css 
        
editor: visual

